http://localhost:5000/api/accounts/christopher

###
http://localhost:5000/api/accounts/noOne


###
POST http://localhost:5000/api/accounts
Content-Type: application/json

{
   "user": "steve",
   "currency": "EUR",
   "balance": 500
}